import torch
import torch.nn as nn
import numpy as np
from random import shuffle
import time
import sys
import os
import math
from utils import calEE
from network import y_net_GNN, lambda_net_GNN, y_net_ResNet, lambda_net_ResNet, y_net_FNN, lambda_net_FNN
import h5py
import random


# test a DNN trained by PDL or EUAT
# test it under different RZF-MRT ratios as an example


os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"


def cal_beamforming2(H, nRZF=25, Pmax=1, sigma2=1):
    # among the APs, randomly choose nRZF APs for using RZF beamforming, and the others use MRT
    BS, L, NT, K = H.shape

    perm = torch.stack([torch.randperm(L) for _ in range(BS)], dim=0)  # BS, L
    idx1 = perm[:, :nRZF]  # use RZF
    idx2 = perm[:, nRZF:]  # use MRT

    idx1_expand = idx1[:, :, None, None].expand(-1, -1, NT, K)
    idx2_expand = idx2[:, :, None, None].expand(-1, -1, NT, K)

    x1 = H.gather(1, idx1_expand)
    x2 = H.gather(1, idx2_expand)

    if NT < K: #RZF
        y1 = torch.matmul(torch.linalg.inv(torch.matmul(x1,x1.mH) + K*sigma2/Pmax*torch.eye(NT)),x1)
    else:
        y1 = torch.matmul(x1,torch.linalg.inv(torch.matmul(x1.mH,x1) + K*sigma2/Pmax*torch.eye(K)))

    y2 = x2 #MRT

    out = torch.empty_like(H)
    out = out.scatter(1, idx1_expand, y1)
    out = out.scatter(1, idx2_expand, y2)
    W = out

    W = W/torch.sqrt(torch.sum(torch.abs(W)**2,2,keepdim=True)) #power norm, [BS,L,NT,K]
    G = torch.matmul(H.mH,W)
    return G



if __name__ == '__main__':
    time_start = time.time()

    K = 10
    L = 25
    NT = 4

    PmaxdBm = 20
    Pmax = 10 ** ((PmaxdBm - 30) / 10)

    sigma2 = 1  # don't change

    Pfix = L * (NT * 0.2 + 0.825)
    a = 1 / 0.4
    b = 0.25e-9 * 1e6
    B = 20e6 / 1e6

    SEqos = 1

    D = 500

    train_number = 20000 # here we only test, thus the hyper-parameters about training are actually invalid
    test_number = min(train_number, 2000)

    set_num1 = 20000
    set_num2 = 2000

    train_H = []
    train_filenames = ['../channels/datasets/CHleng_NT'+str(NT)+'_K'+str(K)+'_L'+str(L)+'_D'+str(D)+'_num'+str(set_num1)+'.mat']
    for filename in train_filenames:
        with h5py.File(filename, 'r') as f:
            real_part = np.array(f['Hset']['real'])
            imag_part = np.array(f['Hset']['imag'])
            H = real_part + 1j * imag_part
            H = np.swapaxes(H, -1, -2)
            train_H.append(torch.from_numpy(H[0:train_number]))

    test_H = []
    test_filenames = ['../channels/datasets/CHleng_NT'+str(NT)+'_K'+str(K)+'_L'+str(L)+'_D'+str(D)+'_num'+str(set_num2)+'.mat'] * 6
    for filename in test_filenames:
        with h5py.File(filename, 'r') as f:
            # H = np.array(f['data']).swapaxes(-1, -2) # use this to load a dataset generated by genDeepMIMO.py or genRealWorld.py
            real_part = np.array(f['Hset']['real'])
            imag_part = np.array(f['Hset']['imag'])
            H = real_part + 1j * imag_part
            H = np.swapaxes(H, -1, -2)
            test_H.append(torch.from_numpy(H[0:test_number]))


    BF = 'RZF-MRT'

    train_G = []
    for m in range(len(train_filenames)):
        train_G.append(cal_beamforming2(train_H[m], 25))  # train with all RZF

    test_G = []
    nRZFset = [25,20,15,10,5,0]
    for m in range(len(test_filenames)):
        test_G.append(cal_beamforming2(test_H[m], nRZFset[m]))  # test with RZF-MRT in different ratios


    # device = torch.device('cpu')
    device = torch.device('cuda:0')

    MAX_EPOCH = 1

    BS = min(100, train_number)
    LEARNING_RATE = 1e-3

    A = 1

    modelName = 'GNN'
    # modelName = 'ResNet'
    # modelName = 'FNN'

    if modelName == 'GNN':
        y_layer = [64]*4
        y_net = y_net_GNN(input_dim=3, hidden_dim=y_layer, output_dim=1)
    elif modelName == 'ResNet':
        y_layer = [64]*7
        y_net = y_net_ResNet(input_dim=3*L, hidden_dim=y_layer, output_dim=1*L)
    elif modelName == 'FNN':
        y_layer = [256]*6
        y_net = y_net_FNN(input_dim=2*L*K*K+1, hidden_dim=y_layer, output_dim=L*K)
    else:
        pass


    y_net.to(device)
    y_optimizer = torch.optim.Adam([{'params': y_net.parameters()}], lr=LEARNING_RATE, weight_decay=0)
    y_scheduler = torch.optim.lr_scheduler.MultiStepLR(y_optimizer, [30, 60, 90, 120], gamma=0.3, last_epoch=-1)


    timestr = time.strftime("%m%d%H%M%S", time.localtime())
    print('model', modelName, 'BF', BF, 'K', K, 'NT', NT, 'L', L, 'D',D, 'Pmax', Pmax, 'range', A, 'sigma2', sigma2, 'Pfix', Pfix, 'a', a, 'b', b, 'B', B, 'SEqos', SEqos, 'time', timestr)
    print('train_number', train_number, 'test_number', test_number, 'batch_size', BS, 'ini_learning_rate', LEARNING_RATE, 'y_layer', y_layer)

    print(train_filenames)
    print(test_filenames)

    is_PDL = True
    if is_PDL:
        PDL_LEARNING_RATE = LEARNING_RATE * .1

        if modelName == 'GNN':
            lam_layer = [32] * 3
            lam_net = lambda_net_GNN(input_dim=3, hidden_dim=lam_layer, output_dim=1)
        elif modelName == 'ResNet':
            lam_layer = [64] * 3
            # lam_net = lambda_net_ResNet(input_dim=3, hidden_dim=lam_layer, output_dim=1)
            lam_net = lambda_net_ResNet(input_dim=3*L, hidden_dim=lam_layer, output_dim=1)
            # lam_net = lambda_net_ResNet(input_dim=3*K, hidden_dim=lam_layer, output_dim=1)
        elif modelName == 'FNN':
            lam_layer = [128] * 4
            lam_net = lambda_net_FNN(input_dim=2*L*K*K+1, hidden_dim=lam_layer, output_dim=K)
        else:
            pass

        lam_net.to(device)
        lam_optimizer = torch.optim.Adam([{'params': lam_net.parameters()}], lr=PDL_LEARNING_RATE, weight_decay=0)
        lam_scheduler = torch.optim.lr_scheduler.MultiStepLR(lam_optimizer, [60, 90, 120], gamma=0.3, last_epoch=-1)

        amp = '50'
        print('PDL', 'lam_layer', lam_layer, 'LR',PDL_LEARNING_RATE, 'amp', amp)

    # hyper-parameters for EUAT
    epoch_UAT = 9999
    T_UAT = 5
    alpha_UAT = 0.1
    is_deH = False
    is_minusG = True
    is_plusG = True
    w_plusG = 1
    k_plusG = 10

    is_EUAT = True # True for loading a model

    if is_EUAT:
        address = 'model_' + '1129185351' + 'RZF' + '_K' + str(K) + '_NT' + str(NT) + '_L' +str(L) + '_D' +str(D) + '.ckp'
        print('EUAT', 'T', T_UAT, 'alpha', alpha_UAT, 'w', w_plusG, 'm', k_plusG)
        print(address)
        y_net.load_state_dict(torch.load(address)['y_net'])
        # y_optimizer.load_state_dict(torch.load(address)['y_optimizer'])
        # y_scheduler.load_state_dict(torch.load(address)['y_scheduler'])
        lam_net.load_state_dict(torch.load(address)['lam_net'])
        # lam_optimizer.load_state_dict(torch.load(address)['lam_optimizer'])
        # lam_scheduler.load_state_dict(torch.load(address)['lam_scheduler'])
        epoch_UAT = 0


    sys.stdout.flush()
    eta = SEqos * torch.ones(BS, K).to(device)
    highestEE = 0

    for epoch in range(MAX_EPOCH):
        # only test
        if epoch % 1 == 0:
            y_net.eval()

            with torch.no_grad():
                sum_train_loss = [0]*len(train_filenames)
                sum_train_error = [0]*len(train_filenames)

                sum_test_loss = [0]*len(test_filenames)
                sum_test_error = [0]*len(test_filenames)

                for bb in range(int(test_number / BS)):
                    for m in range(len(train_filenames)):
                        batch_x = train_G[m][bb * BS:(bb + 1) * BS].to(device)
                        normG = torch.ones(BS,1,1,1).to(device)
                        sqrtnorm = torch.sqrt(normG)
                        batch_x = batch_x / sqrtnorm
                        y_pred = y_net(batch_x, sqrtnorm, Pmax*torch.ones_like(normG))
                        EE, _, _, _, SEperUE, VR = calEE(batch_x*sqrtnorm, y_pred, 1, Pfix, a, b, B, eta, device, training=False)
                        sum_train_loss[m] = sum_train_loss[m] + EE.detach().cpu().numpy()
                        sum_train_error[m] = sum_train_error[m] + VR.detach().cpu().numpy()

                    for m in range(len(test_filenames)):
                        batch_x = test_G[m][bb * BS:(bb + 1) * BS].to(device)
                        normG = torch.ones(BS,1,1,1).to(device) = torch.ones(BS,1,1,1).to(device)
                        sqrtnorm = torch.sqrt(normG)
                        batch_x = batch_x / sqrtnorm
                        y_pred = y_net(batch_x, sqrtnorm, Pmax*torch.ones_like(normG))
                        EE, _, _, _, SEperUE, VR = calEE(batch_x*sqrtnorm, y_pred, 1, Pfix, a, b, B, eta, device, training=False)
                        sum_test_loss[m] = sum_test_loss[m] + EE.detach().cpu().numpy()
                        sum_test_error[m] = sum_test_error[m] + VR.detach().cpu().numpy()

                time_end = time.time()
                print(epoch, "{:.2f}".format(time_end - time_start), end=' ')
                for m in range(len(train_filenames)):
                    print(f"{sum_train_loss[m] / (test_number / BS):.4f}", end=' ')
                    print(f"{sum_train_error[m] / (test_number / BS):.2f}", end=' ')
                print('|', end=' ')
                for m in range(len(test_filenames)):
                    print(f"{sum_test_loss[m] / (test_number / BS):.4f}", end=' ')
                    print(f"{sum_test_error[m] / (test_number / BS):.2f}", end=' ')
                print()
                sys.stdout.flush()
                time_start = time.time()

