clear
clc

K = 4; %number of single-antenna users
Ns = 6; % number of RF chains
NT = 16; % number of BS antennas

Ptot = 40; % in [dBm]

SNR = 0; % don't change, since noise power has been taken into account when generating channels

%% select dataset

% (1) load from those generated by Quadriga, the name of channel variable is ``Hset''

fc = 3.5e9;
load(['../channels/datasets/CH' 'fc' '_NT' num2str(NT) '_K' num2str(K) '_fc' num2str(fc) '_num' num2str(2000) '.mat'])

% d = 0.5;
% load(['../channels/datasets/CH' 'spacing' '_NT' num2str(NT) '_K' num2str(K) '_d' num2str(d) '_num' num2str(2000) '.mat'])

% D = 10;
% r = D/2;
% load(['../channels/datasets/CH' 'hotspot' '_NT' num2str(NT) '_K' num2str(K) '_r' num2str(r) '_num' num2str(2000) '.mat']); 

% Type = 1;
% load(['../channels/datasets/CH' 'type' '_NT' num2str(NT) '_K' num2str(K) '_ty' num2str(type) '_num' num2str(2000) '.mat']); 


% (2) load from those generated by DeepMIMO or Real-world Dataset
% data = h5read(['../channels/datasets/CH' 'o1_3p5' '_NT' num2str(NT) '_K' num2str(K) '_num' num2str(2000) '.mat'], '/data'); %DeepMIMO
% data = h5read(['../channels/datasets/CH' 'city_0_newyork_3p5' '_NT' num2str(NT) '_K' num2str(K) '_num' num2str(2000) '.mat'], '/data');  %DeepMIMO

% data = h5read('../channels/datasets/CHindoor_NT64_K4_num2000.mat', '/data');  %Real-world Dataset

% Hset = data.r + 1j*data.i; % let data being complex numbers

% Hset = Hset(1:NT,:,:); % it can only consider the first 16 antennas, when using the real-world dataset

%%
Time = 2000;

Rsum0 = 0;
Rsum1 = 0;
Rsum2 = 0;
Rsum3 = 0;
Rsum4 = 0;

parfor t = 1:Time
    if mod(t,100) == 0
        fprintf('time %d\n', t);
    end

    %% channel
    % H = sqrt(1/2)*(randn(K,NT)+1j*randn(K,NT)); %Rayleigh channel
    
    H = double(Hset(:,:,t)).' * 10^(Ptot/20); % channels from datasets
    
    if fc > 6e9 % when fc changes, enable these codes
        H = H * (fc/3.5e9)*sqrt(5);
    else
        H = H * (fc/3.5e9);
    end

    %% full-digital precode
    W1 = WMMSE(H,SNR);
    Rsum0 = Rsum0 + calrate(H,W1,K,SNR);

    %% hybrid precode
    [FRF, FBB] = OMP( W1, Ns, H'./abs(H'));
    Rsum1 = Rsum1 + calrate(H,FRF*FBB,K,SNR);

    [FRF,FBB] = MO(W1,Ns);
    Rsum2 = Rsum2 + calrate(H,FRF*FBB,K,SNR);

    [FRF,FBB] = PEM(W1,Ns);
    Rsum3 = Rsum3 + calrate(H,FRF*FBB,K,SNR);

    [FRF,FBB] = SVDp(H,Ns,SNR);
    Rsum4 = Rsum4 + calrate(H,FRF*FBB,K,SNR);

end
WMMSEresult = Rsum0/Time % in [bps/Hz]
OMPresult = Rsum1/Time
MOresult = Rsum2/Time
PEresult = Rsum3/Time
SVDresult = Rsum4/Time

